name: Backend workflow

on:
  push:
    branches: ["main"]

jobs:
  Image-build-push:
    name: Job1
    runs-on: ubuntu-latest

    steps:
      - name: Use custom action for build/push of the image
        uses: org-547/app-2-actions/job-1@main
        with:
          app-component: app-server-2
          container: back-cnt
          port: 5000
          docker-uname: ${{ secrets.DOCKER_UNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
  
  Change-image-tag-and-deploy:
    name: Job2
    needs: [Image-build-push]
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
        working-directory: /home/student/actions-runner/_work/app-server-2/app-server-2/app-server-2

    steps:
      - name: Use custom action for update/deploy app-component
        uses: org-547/app-2-actions/job-2@main
        with:
          not-default-workdir: /home/student/actions-runner/_work/app-server-2/app-server-2
          git-user: 'Tereza'
          email: 'an3146073@gmail.com'
          ssh-priv-key: ${{ secrets.SSH_PRIV_KEY }}
          app-component: 'app-server-2'
          execution-workdir: 'app-server-2'
          git-token: ${{ secrets.GIT_TOKEN }}
          second-component-tag: 'undefined-front-tag'
    
